### ISSUE TITLE
DigitalSignatureServiceSession not serializable even though it claims to be

### ISSUE THREAD

**Issue by klr8** [e-Contract/dssp#1]
From the DigitalSignatureServiceSession JavaDoc:
```java
 * Session object for DSSP. Is serializable to be able to get stored inside an
 * HTTP session context.
```
However, when I try to serialize it I get:
```
java.io.NotSerializableException: com.sun.xml.internal.messaging.saaj.soap.ver1_2.SOAPPart1_2Impl
```

**Comment by fcorneli** [comment]
I can indeed confirm the issue:
```
12:03:11,614 ERROR [be.e_contract.dss.portal.PortalController] 
(ajp-localhost.localdomain/127.0.0.1:8009-2) session serialization error: 
com.sun.xml.messaging.saaj.soap.ver1_2.SOAPPart1_2Impl: 
java.io.NotSerializableException: com.sun.xml.messaging.saaj.soap.ver1_2.SOAPPart1_2Impl
```
Seems like the SAAJ DOM objects don't play well with serialization.

We will release version 1.2.3 of the DSSP client to fix this issue.
Thanks for reporting this to us.

**Comment by klr8** [comment]
Thanks for picking this up so quickly.
As soon as you have 1.2.3 available I'll give it another go.

**Comment by fcorneli** [comment]
Version 1.2.3 has been released. Could you try it again?

**Comment by klr8** [comment]
1.2.3 Indeed fixes the serialization problem.
