### ISSUE TITLE
SignResponseVerificationResult.getSignerIdentity always returns null

### ISSUE THREAD

**Issue by klr8** [e-Contract/dssp#6]
I would like to learn about who signed a document. To get to that information, I'm calling `getSignerIdentity` on the `SignResponseVerificationResult` object returned by `SignResponseVerifier.checkSignResponse`. However, that always seems to return `null`.

Is there something else I need to do to make this work?

I'm using dssp-client 1.2.3.

**Comment by fcorneli** [comment]
Via PendingRequestFactory.createPendingRequest you have to indicate that the DSS should return this signer identity.

**Comment by klr8** [comment]
That indeed seems to work.
Thanks!
